# Generated by Django 5.1.7 on 2025-04-20 16:20

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Note', max_length=255)),
                ('title_slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.URLField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('indent_level', models.PositiveIntegerField(default=0)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='blog.note')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.noterow')),
            ],
            options={
                'ordering': ['note', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('content_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'created_at'], name='blog_note_owner_i_a125a4_idx'),
        ),
        migrations.AddIndex(
            model_name='noterow',
            index=models.Index(fields=['note', 'order'], name='blog_notero_note_id_856756_idx'),
        ),
        migrations.AddIndex(
            model_name='noterow',
            index=models.Index(fields=['note', 'indent_level'], name='blog_notero_note_id_d2ab9f_idx'),
        ),
    ]
